### ISSUE TITLE
bring our tools (unit, e2e, automation,...) together

### ISSUE THREAD

**Issue by jasteuer** [sqe-galerie/bildergalerie#33]
To bring our tools (Vagrant, Travis, SonarQube, PHPUnit, testcafe,...) together, we have to do some steps (which can not be done in the isolated branchs):

- [x] run tests via script in package.json 
note: e2e tests needs different SERVER_URLs:
* something like http://localhost:8888 if travis starts the test (without vagrant). maybe headless?
* something like http://5.5.5.5 if a developer starts the tests from his host machine while server is running in the guest machine with vagrant. not headless, developer want to see the browser window
- [ ] reset db before each e2e test
- [x] (use local installation of testcafe instead of a global one?)
- [x] configure travis ci to run e2e tests
- [x] configure travis ci to run phpunit
- [x] sonar-scanner should collect phpunit coverage reports
- [x] configure travis ci to run sonar-scanner

**Comment by felixble** [comment]
@jasteuer we could solve the issue that we need different SERVER_URLs by providing different config parameters since the settings for our database also depend if travis is running or we are on our development environment. So maybe we should start with #34 ? Then the travis `before_install` script could overwrite the `.env` file with travis specific configuration. The vagrant bootstrap script, however, could set the default configuration for local testing purposes.
